# models/marts/schema.yml
version: 2

models:
  - name: dim_channels
    columns:
      - name: channel_id
        tests:
          - unique
          - not_null
  - name: dim_dates
    columns:
      - name: date_id
        tests:
          - unique
          - not_null
      - name: post_date
        tests:
          - not_null
  - name: fct_messages
    columns:
      - name: message_key
        tests:
          - unique
          - not_null
      - name: channel_id
        tests:
          - relationships:
              to: ref('dim_channels')
              field: channel_id
      - name: post_date_id
        tests:
          - relationships:
              to: ref('dim_dates')
              field: date_id
      

              
              
